[package]
name = "q3"
version = "0.1.0"
authors = ["Jacky <x2x4com@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
type-info = "0.2.1"
